apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: ervdb
spec:
  replicas: 1
  expose:
    - LoadBalancer
  datasources:
    - name: er
      type: postgresql
      properties:
        - name: username
          value: naps
        - name: password
          value: naps
        - name: jdbc-url
          value: jdbc:postgresql://postgresql.user10-er-demo.svc.cluster.local:5432/emergency_response_demo
    - name: jbpm
      type: postgresql
      properties:
        - name: username
          value: rhpam
        - name: password
          value: rhpam
        - name: jdbc-url
          value: jdbc:postgresql://process-service-postgresql.user10-er-demo.svc.cluster.local:5432/rhpam
    - name: dw
      type: postgresql
      properties:
        - name: username
          value: naps
        - name: password
          value: naps
        - name: jdbc-url
          value: jdbc:postgresql://dw-postgresql.user10-er-demo.svc.cluster.local:5432/datawarehouse          
  build:
    source:
      ddl: |
        CREATE DATABASE EmergencyResponse OPTIONS (ANNOTATION 'The EmergencyResponse VDB');
        USE DATABASE EmergencyResponse;

        --############ translators ############
        CREATE FOREIGN DATA WRAPPER postgresql;

        --############ Servers ############
        CREATE SERVER "er" FOREIGN DATA WRAPPER postgresql;
        CREATE SERVER "jbpm" FOREIGN DATA WRAPPER postgresql;
        CREATE SERVER "dw" FOREIGN DATA WRAPPER postgresql;

        --############ Schemas ############
        CREATE SCHEMA erdemo SERVER "er";
        CREATE SCHEMA process SERVER "jbm";
        CREATE SCHEMA datawarehouse SERVER "dw";

        CREATE VIRTUAL SCHEMA EmergencyResponse;

        --############ Schema:erdemo ############
        SET SCHEMA erdemo;

        IMPORT FROM SERVER "er" INTO erdemo OPTIONS (
                "importer.useFullSchemaName" 'false',
                "importer.tableTypes" 'TABLE,VIEW');
