apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: vdbdatasource
spec:
  datasources:
    - access: proxy
      editable: true
      secureJsonData:
        password: foo
      name: DS_DW_VDB
      user: foo
      url: 'ervdb.datavirt:5432'
      jsonData:
        sslmode: disable
      type: postgres
      database: emergencyresponse
  name: vdbdatasources.yaml
