{
 "title": "Mission Commander VDB KPIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "content": "\n# Mission Commander VDB KPIs\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "select sum(numberrescued) from mission"
    }
   ]
  },
  {
   "title": "Total Rescued ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select numbersrescued from totalrescued;"
    }
   ]
  },
  {
   "title": "Top Responders",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "select times as \"time\", totalrescued, responder from topresponders;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 17, "x": 0, "y": 10 },
   "content": "\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "select responder, responseVelocityKmPerHr, incidentId, processInstanceId from fastesttravelvelocities;"
    }
   ]
  },
  {
   "title": "Fastest Travel Velocities",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select responder, responseVelocityKmPerHr, incidentId, processInstanceId from fastesttravelvelocities;"
    }
   ]
  }
 ]
}